## 1. IPython Notebooks
An IPython notebook is made up of a number of cells. Each cell can contain Python code. You can execute a cell by clicking on it and pressing `Shift-Enter`. When you do so, the code in the cell will be executed, and the output of the cell will be displayed beneath the cell. For example, after running the first cell the notebook looks like this:

In [5]:
x = 5
print(x+3)

8


Global variables are shared between cells. Therefore, we can access `x` in the next cell.

In [6]:
print(x+10)

15


By convention, IPython notebooks are expected to be run from top to bottom. Failing to execute some cells or executing cells out of order can result in errors:

In [19]:
# This does not work
print(x+y)

[[ 6  8]
 [10 12]]


In [8]:
# After executing this cell, you can re-evaluate the cell above
y = 3

Please make sure that you are using the correct python environment. You can print out the environment path with the following cell. If you use python2 to work on the exercises and submit your model, you will encounter errors.

In [9]:
import sys
print(sys.version)
if sys.version_info <= (3, 10):
    print("you are using an older version of python. We expect python 3.10.x \nYou can continue with your version but it might cause some issues")

3.13.7 (tags/v3.13.7:bcee1c3, Aug 14 2025, 14:15:11) [MSC v.1944 64 bit (AMD64)]


After you have modified an IPython notebook for one of the assignments by modifying or executing some of its cells, remember to __save your changes__!


## 2. Imports

We start every notebook with a cell containg the important imports. So the first cell of every notebook is the import cell, as this needs to be executed before running any code.


In [10]:
import time
import os
import random
import math
import numpy as np
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
%matplotlib inline
plt.rcParams['figure.figsize'] = (7.0, 5.0) # set default size of plots
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'

# for auto-reloading extenrnal modules
# see http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython
%load_ext autoreload
%autoreload 2

# 3. Numpy Introduction

Numpy is a high performance framework for operations on multi dimensional arrays. It would be a nice tool in your kitty for working on later exercises and your life as a Data Scientist in general. 

In [11]:
# Create a simple (2, 3) numpy array
# [[ 1  2  3]
#  [ 4  5  6]]
a = np.array([[1,2,3], [4,5,6]])

# Print the data type of this array
print(a.dtype)

# print the shape of this array
print(a.shape)

int64
(2, 3)


In [12]:
# Slicing operation 
# Let us take the first two columns from the original array and save it in a new one
b = a[:, :2]
print(b)
print(b.shape)

[[1 2]
 [4 5]]
(2, 2)


In [13]:
# Select elements which satisfy a condition
# Using numpy array makes such a selection trivial
mask = a > 1
new_array = a[mask]
new_array

array([2, 3, 4, 5, 6])

In [14]:
# Do the same thing in a single step
c = a[a>1]
assert np.all(new_array == c) #  np.all() to indicate that all the values need to match

In [15]:
# Mathematical operations
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [16]:
# Element wise operations
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

# Element wise exponential operation
#[[ 2.71828183  7.3890561 ]
#  [20.08553692 54.59815003]] 
print(np.exp(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


A detailed summary of numpy is beyond the scope of this assignment. Please take a look at http://docs.scipy.org/doc/numpy/reference/ for further reference. For this exercise, the tasks we have covered should be enough.

## 4. Notebook convenience
One of the convenient things about jupyter notebooks is the ability to display images, instructions and guide your thought process. You will not have any new clanky windows opening up and everything shall be inline.

In [17]:
# Load the image first
image = Image.open('images/sample_image.jpg')
plt.imshow(image)

FileNotFoundError: [Errno 2] No such file or directory: 'images/sample_image.jpg'

## 5. External Files
Most of your work will involve implementing certain functions in external python files. You can either open external files here in jupter notebook or edit them with your favourite text or python editor.

All files you will have to edit are contained in the `exercise_code` folder. Check out the `Dummy` class in `exercise_code/networks/dummy.py`.

In [18]:
from exercise_code.networks.dummy import Dummy
# Instantiate a "model"
model = Dummy()

## 6. Dummy Machine

Usually, we ask you to train and submit models. You don't need to train anything fancy in this exercise, this is just a sample code to familarize you with the file structure and your future tasks.

You need to make some changes to the `forward()` method in `exercise_01/exercise_code/networks/dummy.py`and set `x` to any integer that is larger than 59. We highlight all locations where you should modify the code with boxes in the respective files.

<div class="alert alert-danger">
    <h3>Warning: Don't modify code outside your assigned boxes</h3>
    <p>Make sure that you don't mutate, rename or remove classes or functions outside the respective assigned boxes!</p><p> You can add new functions if you so desire and feel the need of having them structured outside of our respective boxes but besides later exercises these shouldn't be required.</p>
</div>

In this submission you get a score depending upon the number of test cases you pass. Usually, the total points you can secure is between __0 - 100__. For this exercise, you have __one test cases__ which depends on the output of the `forward()` function. You can check the `exercise_01/exercise_code/tests` folder to have a general feel about the unit tests. Please remember that these test cases are just a sample and the submission server has a set of different test cases. 

In [21]:
from exercise_code.tests.dummy_tests import DummyTest

test_cases = DummyTest(model)
test_cases()

The score of your dummy machine is: 20


## 7. Model Saving
Now you need to save the model. We provide you with all the functionality, so you will only need to execute the next cell.

In [22]:
model.save_model()

<div class="alert alert-danger">
    <h3>Warning</h3>
    <p>You might get an error like this:</p>
    <p>PicklingError: Can't pickle `<class 'exercise_code.test_model.TestModel'>`: it's not the same object as exercise_code.test_class.TestSubmission</p>
    <p>The reason is that we are using autoreload and working on this class during the notebook session. If you get this error simply restart the kernel and rerun the whole script (Kernel -> Restart & Run All) or only the important cells for generating your model.</p>
</div>

## 8. Zip File Creation
Run the following cell to create the zip file for submission, which contains all the exercise code, models, and ipynb notebooks.

In [23]:
from exercise_code.submit import submit_exercise

submit_exercise('../Output/Exercise_01')

relevant folders: ['exercise_code', 'models']
notebooks files: ['1_introduction.ipynb']
Adding folder exercise_code
Adding folder models
Adding notebook 1_introduction.ipynb
Zipping successful! Zip is stored under: C:\Users\andyl\OneDrive - UCA\Documentos\GitHub\modelos\Output\Exercise_01.zip


# Submission Goals

- Goal: implement dummy machine 
- Threshold to this exercise: 60
- You can make multiple submission until the deadline. Your __best submission__ will be shown on the website.